enum FormSteps {
  START = 'START',
  DOMESTIC_ABUSE = 'DOMESTIC_ABUSE',
  QUESTION_2_CONTACT = 'QUESTION_2_CONTACT',
  AGREEMENT = 'AGREEMENT',
  QUESTION_4_HELP = 'QUESTION_4_HELP',
  QUESTION_5_MEDIATION = 'QUESTION_5_MEDIATION',
}

export default FormSteps;
