enum FormSteps {
  START = 'START',
  DOMESTIC_ABUSE = 'DOMESTIC_ABUSE',
  CONTACT_COMFORT = 'CONTACT_COMFORT',
  AGREEMENT = 'AGREEMENT',
  HELP_OPTIONS = 'HELP_OPTIONS',
  MEDIATION_CHECK = 'MEDIATION_CHECK',
}

export default FormSteps;
