enum FormSteps {
  START = 'START',
  QUESTION_1_ABUSE = 'QUESTION_1_ABUSE',
  QUESTION_2_CONTACT = 'QUESTION_2_CONTACT',
  QUESTION_3_AGREE = 'QUESTION_3_AGREE',
  QUESTION_4_HELP = 'QUESTION_4_HELP',
  QUESTION_5_MEDIATION = 'QUESTION_5_MEDIATION',
}

export default FormSteps;
